ArticleProject.Web/Controllers/ArticleController.cs
using ArticleProject.Core.Entities;
using ArticleProject.Data.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;

namespace ArticleProject.Web.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IUnitOfWork _repo;

        public ArticleController(IUnitOfWork repo)
        {
            _repo = repo;
        }
        public IActionResult Index(int id)
        {
            var article =  _repo.CreateRepo<AuthorPost,int>().GetById(id);
            var mappedPost =  new AuthorPostViewModel()
            {
                Id = article.Id,
                UserId = article.UserId,
                UserName = article.UserName,
                FullName = article.FullName,
                AuthorId = article.AuthorId,
                CategoryId = article.CategoryId,
                CreatedAt = article.CreatedAt,
                PostCategory = article.PostCategory,
                PostDescription = article.PostDescription,
                PostImageName = article.PostImageUrl,
                PostTitle = article.PostTitle
            };
            return View(mappedPost);
        }
    }
}

ArticleProject.Web/Controllers/HomeController.cs
using ArticleProject.Core.Entities;
using ArticleProject.Data.IRepository;
using ArticleProject.Data.Specifications.PostsSpecifications;
using ArticleProject.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Security.Claims;
using X.PagedList.Extensions;

namespace ArticleProject.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IUnitOfWork _repo;

        public HomeController(ILogger<HomeController> logger,IUnitOfWork repo)
        {
            _logger = logger;
            _repo = repo;
        }

        public async Task<IActionResult> Index(string? searchingItme, string catName, int pageSize = 6, int? pageIndex = 1)
        {
            var posts = await _repo.CreateRepo<AuthorPost, int>().GetAllAsyncWithSpecification(new PostsForHomeSpecs(catName, searchingItme));
            var mappedPost = posts.Select(p => new AuthorPostViewModel()
            {
                Id = p.Id,
                UserId = p.UserId,
                UserName = p.UserName,
                FullName = p.FullName,
                AuthorId = p.AuthorId,
                CategoryId = p.CategoryId,
                CreatedAt = p.CreatedAt,
                PostCategory = p.PostCategory,
                PostDescription = p.PostDescription,
                PostImageName = p.PostImageUrl,
                PostTitle = p.PostTitle
            });
            ViewBag.currentName = catName;
            return View(mappedPost.ToPagedList(pageIndex ?? 1, pageSize));
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ArticleProject.Web/Views/Home/Index.cshtml
@model IEnumerable<AuthorPostViewModel>;
@inject SignInManager<IdentityUser> SignInManager

@inject IUnitOfWork _repo;
@{
    ViewData["Title"] = "Home Page";
    var categories = await _repo.CreateRepo<Category, int>().GetAllAsync();
}

<header class="text-center text-white bg-primary masthead">
    <div class="container">
        <img class="img-fluid d-block mx-auto mb-5" src="~/img/profile.png">
        <h1 style="font-family: Cairo, sans-serif;">مقالاتي</h1>
        <hr class="star-light">
        <h2 class="font-weight-light mb-0" style="font-family: Cairo, sans-serif;">مرحبا بك في موقع مقالاتي</h2>
        <h2 class="font-weight-light mb-0" style="font-family: Cairo, sans-serif;margin: 11px;font-size: 21px;">&nbsp; :) يسعدنا انضمامك معنا&nbsp;</h2>
    </div>
    @if (!SignInManager.IsSignedIn(User))
    {
        <a href="/Identity/account/login" class="btn btn-primary" type="button" style="width: 254.5625px;background: var(--bs-blue);font-family: Cairo, sans-serif;height: 50px;margin: 5px;"><i class="fa fa-sign-in"></i><span style="margin: 15px;">انضم الان&nbsp;</span></a>
    }
</header>


<section id="portfolio" class="portfolio">
    <div class="container">
        <h2 class="text-uppercase text-center text-secondary bounce animated" style="font-family: Cairo, sans-serif;">اخر المقالات</h2>
        <div>
            <nav class="navbar navbar-dark navbar-expand-lg bg-secondary navigation-clean-search" style="margin: 20px;">
                <div class="container">
                    <button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navcol-1">
                        <ul class="navbar-nav">
                            <li class="nav-item"></li>
                            <li class="nav-item"></li>
                            <li class="nav-item"></li>
                        </ul>
                        <form class="me-auto search-form" asp-action="Index">
                            <div class="d-flex align-items-center">
                                <label class="form-label d-flex mb-0" for="search-field">
                                    <i class="fa fa-search"></i>
                                </label>
                                <input class="form-control search-field text-white" type="text" id="search-field" name="searchingItme" placeholder="ابحث عن مقالة" style="font-family: Cairo, sans-serif;">
                                <input value="بحث" type="submit" />
                            </div>
                        </form>
                        <ul class="navbar-nav">
                            @foreach (var item in categories)
                            {
                                <li class="nav-item"><a class="nav-link @(ViewBag.currentName==item.Name?"active":"")" asp-controller="Home" asp-action="Index" asp-route-catName="@item.Name" style="font-family: Cairo, sans-serif;">@item.Name</a></li>
                            }
                            <li class="nav-item"><a class="nav-link @(ViewBag.currentName==null?"active":"")" asp-controller="Home" asp-action="Index" asp-route-catName="@null" style="font-family: Cairo, sans-serif;">جميع الاصناف</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <hr class="star-dark mb-5">
        <div class="row row-cols-3">
            @foreach (var item in Model)
            {
                <div class="col" data-bss-hover-animate="pulse" style="margin: 0;margin-top: 10px;">
                    <div class="card" style="margin: 10;">
                        <img class="card-img-top w-100 d-block" style="height:160px;" src="~/img/PostImages/@Html.DisplayFor(model=>item.PostImageName)">
                        <div class="card-body">
                            <h4 class="text-center card-title" style="font-family: Cairo, sans-serif;">@item.PostTitle</h4><a class="btn btn-primary float-end" role="button" style="font-family: Cairo, sans-serif;width: 149.875px;" asp-controller="Article" asp-action="Index" asp-route-id="@item.Id">قراءة</a>
                        </div>
                    </div>
                </div>
            }
        </div>
        <nav class="text-center float-end" style="font-family: Lato, sans-serif;border-color: var(--bs-red);margin: 10px;">
            @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { pageIndex = page }),
                     new X.PagedList.Mvc.Core.PagedListRenderOptions
            {
                DisplayItemSliceAndTotal = false,
                ContainerDivClasses = new[] { "navigation" },
                MaximumPageNumbersToDisplay = 5,
                UlElementClasses = new[] { "pagination justify-content-center" },
                LiElementClasses = new[] { "page-item" },
                PageClasses = new[] { "page-link" },

            })
        </nav>

</section>
<section class="text-white bg-primary mb-0" id="about">
    <div class="container">
        <h2 class="text-uppercase text-center text-white" style="font-family: Cairo, sans-serif;">حول الموقع</h2>
        <hr class="star-light mb-5">
        <div class="row align-items-center">
            <div class="col">
                <p class="lead text-center" style="font-family: Cairo, sans-serif;">نحن نوفر لك الدعم الكامل لنشر مقالاتك ومشاركتها مع الاخرين . حيث ان موقع مقالتي يضمن لك كافة الحقوق للمقالات التي تنشرها&nbsp; على الموقع&nbsp;</p>
            </div>
        </div>
        @if (!SignInManager.IsSignedIn(User))
        {
            <div class="text-center mt-4"><a class="btn btn-outline-light btn-xl" role="button" href="/Identity/account/login"><i class="fa fa-american-sign-language-interpreting me-2"></i><span style="font-family: Cairo, sans-serif;">اشترك الان وانضم معنا&nbsp;</span></a></div>
        }
    </div>
</section>
<section id="contact">
    <div class="container">
        <h2 class="text-uppercase text-center text-secondary mb-0" style="font-family: Cairo, sans-serif;">تواصل معنا&nbsp;</h2>
        <hr class="star-dark mb-5">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <form id="contactForm" name="sentMessage" novalidate="novalidate">
                    <div class="control-group">
                        <div class="mb-0 form-floating controls pb-2"><input class="form-control" type="text" id="name" required="" placeholder="الاسم" style="font-family: Cairo, sans-serif;"><label class="form-label">Name</label><small class="form-text text-danger help-block"></small></div>
                    </div>
                    <div class="control-group">
                        <div class="mb-0 form-floating controls pb-2"><input class="form-control" type="email" id="email" required="" placeholder="Email Address" style="font-family: Cairo, sans-serif;"><label class="form-label">Email Address</label><small class="form-text text-danger help-block"></small></div>
                    </div>
                    <div class="control-group">
                        <div class="mb-0 form-floating controls pb-2"><input class="form-control" type="tel" id="phone" required="" placeholder="Phone Number" style="font-family: Cairo, sans-serif;"><label class="form-label">Phone Number</label><small class="form-text text-danger help-block"></small></div>
                    </div>
                    <div class="control-group">
                        <div class="mb-5 form-floating controls pb-2"><textarea class="form-control" id="message" required="" placeholder="Message" style="height: 150px;font-family: Cairo, sans-serif;"></textarea><label class="form-label">Message</label><small class="form-text text-danger help-block"></small></div>
                    </div>
                    <div id="success"></div>
                    <div><button class="btn btn-primary float-end btn-xl" id="sendMessageButton" type="submit" style="font-family: Cairo, sans-serif;">ارسل</button></div>
                </form>
            </div>
        </div>
    </div>
</section>