ArticleProject.Web/Controllers/AllUsersController.cs
using ArticleProject.Core.Entities;
using ArticleProject.Data.IRepository;
using ArticleProject.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using X.PagedList.Extensions;

namespace ArticleProject.Web.Controllers
{
    public class AllUsersController : Controller
    {
        private readonly IUnitOfWork _repo;

        public AllUsersController(IUnitOfWork repo)
        {
            _repo = repo;
        }
        public async Task<IActionResult> Index(int? pageIndex, int pageSize = 3)
        {
            var authors = await _repo.CreateRepo<Author,int>().GetAllAsync();
            var mappedAuthors = authors.Select(a => new AuthorViewModel
            {
                Id = a.Id,
                UserId = a.UserId,
                UserName = a.UserName,
                FullName = a.FullName,
                PictureUrl = a.PictureUrl,
                Bio = a.Bio,
                FaceBookLink = a.FaceBookLink,
                InstegramLink = a.InstegramLink,
                XSiteLink = a.XSiteLink
            });
            return View(mappedAuthors.ToPagedList(pageIndex??1,pageSize));
        }
    }
}

ArticleProject.Web/Controllers/AuthorController.cs
using ArticleProject.Core.Entities;
using ArticleProject.Data.IRepository;
using ArticleProject.Data.Specifications.AuthorSpecifications;
using ArticleProject.Web.Helper;
using ArticleProject.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ArticleProject.Web.Controllers
{
    [Authorize]
    public class AuthorController : Controller
    {
        private readonly IUnitOfWork _repo;
        private readonly IAuthorizationService _auth;

        public AuthorController(IUnitOfWork repo, IAuthorizationService auth)
        {
            _repo = repo;
            _auth = auth;
        }
        // GET: AuthorController
        [Authorize("Admin")]
        public async Task<IActionResult> Index(string searchItem)
        {
            List<Author> authors;
            if (searchItem is null)
            {
                authors = await _repo.CreateRepo<Author, int>().GetAllAsync();
            }
            else
            {
                authors = await _repo.CreateRepo<Author, int>().GetAllAsyncWithSpecification(new AuthorSearchingItem(searchItem));
            }
            var mappedAuthors = authors.Select(a => new AuthorViewModel
            {
                Id = a.Id,
                UserId = a.UserId,
                UserName = a.UserName,
                FullName = a.FullName,
                PictureUrl = a.PictureUrl,
                Bio = a.Bio,
                FaceBookLink = a.FaceBookLink,
                InstegramLink = a.InstegramLink,
                XSiteLink = a.XSiteLink
            });
            return View(mappedAuthors);
        }

        // GET: AuthorController/Edit/5
        public IActionResult Edit(int id)
        {
            var author = _repo.CreateRepo<Author, int>().GetById(id);
            var mappedAuthor = new AuthorViewModel()
            {
                Id = author.Id,
                UserId = author.UserId,
                UserName = author.UserName,
                FullName = author.FullName,
                PictureUrl = author.PictureUrl,
                Bio = author.Bio,
                FaceBookLink = author.FaceBookLink,
                InstegramLink = author.InstegramLink,
                XSiteLink = author.XSiteLink
            };
            return View(mappedAuthor);
        }

        // POST: AuthorController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, AuthorViewModel input)
        {
            try
            {
                var author = _repo.CreateRepo<Author, int>().GetById(id.Value);
                if (input.PictureFromUser is not null)
                {
                    if (author.PictureUrl is not null)
                        FileSettings.DeleteFile(author.PictureUrl, "UsersImages");
                    author.PictureUrl = FileSettings.UploadFile(input.PictureFromUser, "UsersImages");
                }
                author.FullName = input.FullName;
                author.Bio = input.Bio;
                author.XSiteLink = input.XSiteLink;
                author.FaceBookLink = input.FaceBookLink;
                author.InstegramLink = input.InstegramLink;

                var updateResult = _repo.CreateRepo<Author, int>().Update(id.Value, author);
                if (updateResult == 1)
                {
                    await _repo.CompleteAsync();
                    var result = await _auth.AuthorizeAsync(User, "Admin");
                    if (result.Succeeded)
                        return RedirectToAction(nameof(Index));
                    else return RedirectToAction("Index", "Admin");
                }
                return View(input);
            }
            catch
            {
                return View(input);
            }
        }
        [Authorize("Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var author = _repo.CreateRepo<Author, int>().GetById(id);
            FileSettings.DeleteFile(author.PictureUrl, "UsersImages");
            _repo.CreateRepo<Author, int>().Delete(id);
            await _repo.CompleteAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

ArticleProject.Web/Controllers/CategoriesController.cs
using ArticleProject.Core.Entities;
using ArticleProject.Data.IRepository;
using ArticleProject.Data.Specifications.CategorySpecifications;
using ArticleProject.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using X.PagedList.Extensions;

namespace ArticleProject.Web.Controllers
{
    [Authorize]
    public class CategoriesController : Controller
    {
        private readonly IUnitOfWork _repo;

        public CategoriesController(IUnitOfWork repo)
        {
            _repo = repo;
        }
        public async Task<IActionResult> Index(string? searchItem, int? pageIndex = 1, int pageSize=3)
        {
            List<Category> cats;
            var specsParam = new CategorySearchingItem(searchItem, pageIndex, pageSize);
                cats = await _repo.CreateRepo<Category, int>().GetAllAsyncWithSpecification(specsParam);
            var mappedCats = cats.Select(c => new CategoryViewModel()
            {
                Id = c.Id,
                Name = c.Name
            }).ToList();

            return View(mappedCats.ToPagedList(pageIndex ?? 1, pageSize));
        }
        [HttpGet]
        public async Task<IActionResult> CreateCategory()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateCategory(CategoryViewModel input)
        {
            if (ModelState.IsValid)
            {
                var mappedCagegory = new Category()
                {
                    Name = input.Name
                };
                var result = await _repo.CreateRepo<Category, int>().AddAsync(mappedCagegory);

                if (result == 1)
                {
                    await _repo.CompleteAsync();
                    return RedirectToAction("Index");
                }

                else
                    return View(input);
            }
            return View(input);
        }
        [HttpGet]
        public async Task<IActionResult> Details(int? id, string viewName = "Details")
        {
            if (id.HasValue)
            {
                var cat = _repo.CreateRepo<Category, int>().GetById(id.Value);
                var mappedCat = new CategoryViewModel()
                {
                    Id = cat.Id,
                    Name = cat.Name
                };
                return View(viewName, mappedCat);
            }
            return BadRequest();
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            return await Details(id, "Edit");
        }
        [HttpPost]
        public async Task<IActionResult> Edit(CategoryViewModel input)
        {
            if (ModelState.IsValid)
            {
                var cat = _repo.CreateRepo<Category, int>().GetById(input.Id.Value);
                cat.Name = input.Name;
                var result = _repo.CreateRepo<Category, int>().Update(input.Id.Value, cat);
                await _repo.CompleteAsync();
                return RedirectToAction("Index");
            }
            return View(input);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            var cat = _repo.CreateRepo<Category, int>().Delete(id.Value);
            await _repo.CompleteAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

ArticleProject.Web/Controllers/PostsController.cs
using ArticleProject.Core.Entities;
using ArticleProject.Data.IRepository;
using ArticleProject.Data.Specifications.PostsSpecifications;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using X.PagedList.Extensions;
using System.Security.Claims;
using Microsoft.Extensions.Hosting;
using ArticleProject.Web.Helper;
using ArticleProject.Data.Specifications.AuthorSpecifications;

namespace ArticleProject.Web.Controllers
{
    [Authorize]
    public class PostsController : Controller
    {
        private readonly IUnitOfWork _repo;
        private readonly IAuthorizationService _authorizationService;

        public PostsController(IUnitOfWork repo,
                               IAuthorizationService authorizationService)
        {
            _repo = repo;
            _authorizationService = authorizationService;
        }
        public async Task<IActionResult> Index(string? searchItem, int? pageIndex, int pageSize = 3)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).ToString().Split(":")[2].Trim();
            List<AuthorPost> posts;
            if (await isAdmin())
            {
                posts = await _repo.CreateRepo<AuthorPost, int>().GetAllAsyncWithSpecification(new PostsSearchingItem(searchItem));
            }
            else
            {
                posts = await _repo.CreateRepo<AuthorPost, int>().GetAllAsyncWithSpecification(new PostsSearchingItem(userId, searchItem));
            }
            var mappedPost = posts.Select(p => new AuthorPostViewModel()
            {
                Id = p.Id,
                UserId = userId,
                UserName = p.UserName,
                FullName = p.FullName,
                AuthorId = p.AuthorId,
                CategoryId = p.CategoryId,
                CreatedAt = p.CreatedAt,
                PostCategory = p.PostCategory,
                PostDescription = p.PostDescription,
                PostImageName = p.PostImageUrl,
                PostTitle = p.PostTitle
            });
            return View(mappedPost.ToPagedList(pageIndex ?? 1, pageSize));
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(AuthorPostViewModel input)
        {
            if (!ModelState.IsValid) return View(input);
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).ToString().Split(":")[2].Trim();
            var authors = await _repo.CreateRepo<Author, int>().GetAllAsyncWithSpecification(new AuthorSearchingItem(userId));
            var author = authors.FirstOrDefault();
            var mappedPost = new AuthorPost()
            {
                Id = input.Id,
                UserId = userId,
                UserName = author.UserName,
                FullName = author.FullName,
                AuthorId = author.Id,
                CategoryId = input.CategoryId,
                CreatedAt = input.CreatedAt,
                PostCategory = _repo.CreateRepo<Category, int>().GetById(input.CategoryId).Name,
                PostDescription = input.PostDescription,
                PostImageUrl = FileSettings.UploadFile(input.PostImageUrl, "PostImages"),
                PostTitle = input.PostTitle
            };
            await _repo.CreateRepo<AuthorPost, int>().AddAsync(mappedPost);
            await _repo.CompleteAsync();
            return RedirectToAction("index");
        }
        public async Task<IActionResult> Details(int? id, string viewName = "Details")
        {
            if (id.Value < 0 || id is null) return BadRequest();
            var post = _repo.CreateRepo<AuthorPost, int>().GetById(id.Value);
            var mappedPost = new AuthorPostViewModel()
            {
                Id = post.Id,
                UserId = post.UserId,
                UserName = post.UserName,
                FullName = post.FullName,
                AuthorId = post.AuthorId,
                CategoryId = post.CategoryId,
                CreatedAt = post.CreatedAt,
                PostCategory = post.PostCategory,
                PostDescription = post.PostDescription,
                PostImageName = post.PostImageUrl,
                PostTitle = post.PostTitle
            };
            return View(viewName, mappedPost);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            return await Details(id.Value, "Edit");
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int? id, AuthorPostViewModel input)
        {
            if (ModelState.IsValid)
            {
                if (input.Id == id)
                {
                    var post = _repo.CreateRepo<AuthorPost, int>().GetById(id.Value);
                    if (input.PostImageUrl is not null)
                    {
                        FileSettings.DeleteFile(post.PostImageUrl, "PostImages");
                        post.PostImageUrl = FileSettings.UploadFile(input.PostImageUrl, "PostImages");
                    }
                    post.PostTitle = input.PostTitle;
                    post.PostDescription = input.PostDescription;
                    post.CategoryId = input.CategoryId;
                    post.PostCategory = _repo.CreateRepo<Category, int>().GetById(input.CategoryId).Name;
                    var result = _repo.CreateRepo<AuthorPost, int>().Update(id.Value, post);
                    if (result == 1)
                    {
                        await _repo.CompleteAsync();
                        if (await isAdmin()) return RedirectToAction("Index");
                        else return RedirectToAction("Index", "Admin");
                    }
                }
            }
            return View(input);
        }
        public IActionResult Delete(int? id)
        {
            var image = _repo.CreateRepo<AuthorPost, int>().GetById(id.Value).PostImageUrl;
            if (image != null)
            {
                FileSettings.DeleteFile(image, "PostImages");
            }
            _repo.CreateRepo<AuthorPost, int>().Delete(id.Value);
            return RedirectToAction("Index");
        }

        private async Task<bool> isAdmin()
        {
            var result = await _authorizationService.AuthorizeAsync(User, "Admin");
            return result.Succeeded;
        }
    }
}

ArticleProject.Web/Views/Shared/_AdminLayout.cshtml
@using System.Security.Claims
@using ArticleProject.Data.Specifications.AuthorSpecifications
@inject IUnitOfWork _repo;
@inject IAuthorizationService _auth;
@{
    var userId = User.FindFirst(ClaimTypes.NameIdentifier).ToString().Split(":")[2].Trim();
    var ids = await _repo.CreateRepo<Author, int>().GetAllAsyncWithSpecification(new AuthorSearchingItem(userId));
    var specificId = ids.FirstOrDefault().Id;
    var result = await _auth.AuthorizeAsync(User, "Admin");
}
<!DOCTYPE html>
<html style="font-family: Cairo, sans-serif;">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>مقالتي</title>
    <meta name="description" content="موقع يسمح لك بنشر مقالات ومشاركتها مع الاخرين">
    <link rel="stylesheet" href="~/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cairo&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito+Sans">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Slab:300,400|Roboto:300,400,700">
    <link rel="stylesheet" href="~/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="~/fonts/ionicons.min.css">
    <link rel="stylesheet" href="~/css/Animation-Cards-1.css">
    <link rel="stylesheet" href="~/css/Animation-Cards.css">
    <link rel="stylesheet" href="~/css/Article-Cards.css">
    <link rel="stylesheet" href="~/css/Article-Clean.css">
    <link rel="stylesheet" href="~/css/Article-List.css">
    <link rel="stylesheet" href="~/css/Black-Navbar.css">
    <link rel="stylesheet" href="~/css/dh-card-image-left-dark.css">
    <link rel="stylesheet" href="~/css/dh-navbar-inverse.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">
    <link rel="stylesheet" href="~/css/Login-Form-Clean.css">
    <link rel="stylesheet" href="~/css/Login-Form-Dark.css">
    <link rel="stylesheet" href="~/css/Navbar---Apple-1.css">
    <link rel="stylesheet" href="~/css/Navbar---Apple.css">
    <link rel="stylesheet" href="~/css/Navigation-with-Button.css">
    <link rel="stylesheet" href="~/css/Navigation-with-Search.css">
    <link rel="stylesheet" href="~/css/News-Cards.css">
    <link rel="stylesheet" href="~/css/Off-Canvas-Sidebar-Drawer-Navbar.css">
    <link rel="stylesheet" href="~/css/Responsive-UI-Card-02.css">
    <link rel="stylesheet" href="~/css/Right-Sidebar.css">
    <link rel="stylesheet" href="~/css/Sidebar-Menu-1.css">
    <link rel="stylesheet" href="~/css/Sidebar-Menu.css">
    <link rel="stylesheet" href="~/css/SIdebar-Responsive-2-1.css">
    <link rel="stylesheet" href="~/css/SIdebar-Responsive-2.css">
    <link rel="stylesheet" href="~/css/Sidebar-right-opening.css">
    <link rel="stylesheet" href="~/css/Social-Icons.css">
    <link rel="stylesheet" href="~/css/Soft-UI-Aside-Navbar.css">
    <link rel="stylesheet" href="~/css/Studious-sidebar.css">
    <link rel="stylesheet" href="~/css/Team-Boxed.css">
    <link rel="stylesheet" href="~/css/Vertical-Left-SideBar-by-Jigar-Mistry.css">
</head>

<body style="font-family: Cairo;">
    <nav class="navbar navbar-light navbar-expand-lg navigation-clean-button">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">الرجوع الى الصفحة</a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="navbar-nav me-auto"></ul>
                <span class="navbar-text actions">
                    <a asp-controller="Author" asp-action="Edit" asp-route-id="@specificId" class="btn btn-light action-button" role="button" style="margin: 5px;width: 116.7px;margin-right: 0px;font-family: Cairo, sans-serif;">حسابي</a>
                    <a class="btn btn-light action-button" role="button" asp-controller="Posts" asp-action="Index" style="margin: 5px;width: 116.7px;margin-right: 0px;font-family: Cairo, sans-serif;">المقالات</a>
                    @if (result.Succeeded)
                    {
                        <a class="btn btn-light action-button" role="button" asp-controller="Categories" asp-action="Index" style="margin: 5px;width: 116.7px;margin-right: 0px;font-family: Cairo, sans-serif;">الفئات</a>
                        <a class="btn btn-light action-button" role="button" asp-controller="Author" asp-action="Index" style="margin: 5px;width: 116.7px;margin-right: 0px;font-family: Cairo, sans-serif;">المستخدمين</a>
                    }
                    <a class="btn btn-light action-button" role="button" asp-controller="home" asp-action="Index" style="margin: 5px;width: 116.7px;margin-right: 0px;font-family: Cairo, sans-serif;background: var(--bs-red);">الرئيسة</a>
                </span>
            </div>
        </div>
    </nav>
    <div class="container" style="font-family:Cairo;direction:rtl">
        @RenderBody()
    </div>
    <script src="~/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/js/bs-init-1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
    <script src="~/js/Off-Canvas-Sidebar-Drawer-Navbar.js"></script>
    <script src="~/js/freelancer.js"></script>
    <script src="~/js/Off-Canvas-Sidebar-Drawer-Navbar-1.js"></script>
    <script src="~/js/Studious-sidebar.js"></script>
    <script src="~/js/bs-init.js"></script>
    <script src="~/js/chart.min.js"></script>
    <script src="~/js/Navbar---Apple.js"></script>
    <script src="~/js/Right-Sidebar.js"></script>
    <script src="~/js/Sidebar-Menu.js"></script>
    <script src="~/js/Sidebar-right-opening.js"></script>
    <script src="~/js/theme.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>